spring:
  application:
    name: api-gateway

  profiles:
    active: dev

  # Database Configuration
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/api_gateway}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:5N1K2025SecretTokenKey}
  access-token-expiration: 900000 # 15 minutes
  refresh-token-expiration: 604800000 # 7 days

# Google OAuth2 Configuration
google:
  oauth2:
    client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
    issuer: https://accounts.google.com
    jwks-uri: https://www.googleapis.com/oauth2/v3/certs

# Rate Limiting Configuration
rate-limit:
  capacity: 100
  refill-period: 300 # 5 minutes
  refill-tokens: 100

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080,https://api.5n1k.io}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:

# Logging Configuration
logging:
  level:
    com.ehocam.api_gateway: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---
# Development Profile
spring:
  config:
    activate:
      on-profile: dev

  # Local Redis Configuration for Development
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.ehocam.api_gateway: DEBUG
    org.springframework.security: DEBUG

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod

  # Production Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    com.ehocam.api_gateway: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
